name: recruit
channels:
  - conda-forge
dependencies:
  - c-compiler
  - clang==16.0.6
  - clang-tools==16.0.6
  - cmake>=3.17
  - cppcheck==2.10.3
  - cudatoolkit-dev>=10.0
  - cxx-compiler
  - doxygen
  - gcovr
  - include-what-you-use
  - make
  - pip
  - python>=3.10
  - yamllint==1.31.0
  - pip:
      - pre-commit
      - bump2version==1.0.1
      - clang-format==16.0.6
      - cmakelang==0.6.13
      - flawfinder==2.0.19
